// This is the file which will export all of the strings that will be used in this app
export default {
    AboutUs: 'About Us',
    PrivacyPolicy: 'Privacy Policy',
    TermsOfService: 'Terms of Service',
    FAQ: 'FAQ',
    ContactUs: 'Contact Us',
    FollowUsOnSocialMedia: 'Follow Us on Social Media',
    IWantToLearn: 'I want to learn...',
    Python: 'Python',
    Java: 'Java',
    JavaScript: 'JavaScript',
    ReactJS: 'React.js',
    ReactNative: 'React Native',
    Firestore: 'Firestore',
    Installation: 'Installation',
    Documentation: 'Documentation',
    JavaDocumentation: "Java Documentation: https://docs.oracle.com/en/java/javase/14/",
    DownloadJava: 'Download Java: https://java.com/en/download/',
    DownloadEclipse: 'Download Eclipse IDE: https://www.eclipse.org/downloads/packages/release/neon/2/eclipse-ide-java-developers',
    MoreComingSoon: 'More Coming Soon!',
    SubscribeToKnowWhenGuideIsAvailable: 'Subscribe to our email list to know when the full guide is available!',
    Subscribe: 'Subscribe',
    DownloadVSCode: 'Download Visual Studio Code: https://code.visualstudio.com/download',
    JavaScriptDocumentation: 'JavaScript Documentation: https://developer.mozilla.org/en-US/docs/Web/JavaScript',
    Learn: 'Learn',
    Practice: 'Practice',
    Resources: 'Resources',
    WantToLearnMore: 'Want to learn more?',
    ReachOutToUs: 'Reach out to us @CodingIsUs on Instagram!',
    WatchTheVideoBelow: 'Watch the video below to get started!',
    Practice: 'Practice',
    CodingIsUsRequiresInternet: 'Coding is Us requires an active internet connection! Please try again when you are connected.',
    Whoops: 'Whoops',
    TryAgain: 'Try Again',
    Facebook: 'Facebook',
    Instagram: 'Instagram',
    CustomContentAndPracticeComingSoon: 'Custom Content & Practice Coming Soon!',
    Okay: 'Okay',
    Update: 'Update',
    UpdateAvailable: 'There\'s an update available! Press "Okay" to install it now.',
    CheckingForUpdate: 'Checking for update...',
    DownloadingUpdate: 'Downloading update...',
    InstallingUpdate: 'Installing update...',
    MarkAsDone: 'Mark as Done',
    CodingIsUs: 'Coding is Us',
    AllGuides: 'All Guides',
}